# Generated by Django 4.2.6 on 2024-11-29 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_la_chambre', models.CharField(choices=[('01 Rose', '01 Rose'), ('02 Tulipe', '02 Tulipe'), ('03 Orchidée', '03 Orchidée'), ('04 Lys', '04 Lys'), ('05 Magnolia', '05 Magnolia'), ('06 Violette', '06 Violette'), ('07 Dahlia', '07 Dahlia'), ('08 Pivoine', '08 Pivoine'), ('09 Iris', '09 Iris'), ('10 Chrysanthème', '10 Chrysanthème'), ('11 Jonquille', '11 Jonquille'), ('12 Anémone', '12 Anémone'), ('13 Bleuet', '13 Bleuet'), ('14 Coquelicot', '14 Coquelicot'), ('15 Jasmin', '15 Jasmin'), ('16 Hibiscus', '16 Hibiscus'), ('17 Glycine', '17 Glycine'), ('18 Azalée', '18 Azalée'), ('19 Camélia', '19 Camélia'), ('20 Freesia', '20 Freesia')], max_length=50)),
                ('date_enregistrement', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('date_mise_a_jour', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_de_jours', models.PositiveIntegerField()),
                ('nom_du_client', models.CharField(max_length=255)),
                ('adresse_client', models.TextField(blank=True, null=True)),
                ('telephone_client', models.CharField(blank=True, max_length=15, null=True)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kenge.chambre')),
            ],
        ),
    ]
